"""empty message

Revision ID: 55d3ddf2077c
Revises: 8f4bac0bce3f
Create Date: 2020-02-07 00:34:35.555479

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '55d3ddf2077c'
down_revision = '8f4bac0bce3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('answers', sa.String(length=1000), nullable=False))
    op.drop_column('answers', 'text')
    op.drop_column('answers', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('name', mysql.VARCHAR(length=80), nullable=False))
    op.add_column('answers', sa.Column('text', mysql.VARCHAR(length=1000), nullable=False))
    op.drop_column('answers', 'answers')
    # ### end Alembic commands ###
