"""empty message

Revision ID: 8e04db7911e7
Revises: 0fe746cb816b
Create Date: 2020-01-25 17:40:12.020833

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8e04db7911e7'
down_revision = '0fe746cb816b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lawyer', sa.Column('lawfirm', sa.String(length=120), nullable=False))
    op.drop_column('lawyer', 'lowfirm')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lawyer', sa.Column('lowfirm', mysql.VARCHAR(length=120), nullable=False))
    op.drop_column('lawyer', 'lawfirm')
    # ### end Alembic commands ###
